#!/usr/bin/php -q
<?php

// Extract SRS bounds from http://www.epsg-registry.org/ GML file with EPSG metadata
    
$txt = file_get_contents("GmlDictionary.xml");

// namespaces seem to confuse xpath()
$txt = str_replace("xlink:","",$txt);
$txt = str_replace("gml:","",$txt);
$txt = str_replace("gmd:","",$txt);
$txt = str_replace("gco:","",$txt);
$txt = str_replace("epsg:","",$txt);

$xml = simplexml_load_string($txt);

echo 'epsg:',"\n(\n";

$i = 0;
foreach($xml->xpath("dictionaryEntry/ProjectedCRS") as $proj)
{
    $id = $proj->xpath("identifier")[0];
    $epsg = explode(':',$id)[6];

    $name = $proj->xpath("name")[0];
    $scope = @esc($proj->xpath("scope")[0]);
    $source = @esc($proj->xpath("metaDataProperty/CommonMetaData/informationSource")[0]);
    $revision = @$proj->xpath("metaDataProperty/CommonMetaData/revisionDate")[0];
    $deprecated = @$proj->xpath("metaDataProperty/CommonMetaData/isDeprecated")[0];
    
    $domain = $proj->xpath("domainOfValidity")[0]['href'];
    $area = $xml->xpath("dictionaryEntry/ExtentDefinition[identifier='$domain']")[0];
    $box = $area->xpath("extent/AreaOfUse/geographicElement/EX_GeographicBoundingBox");
    if(!empty($box))
    {
        if($i++ > 0)
            echo ",\n";
        
        $box = $box[0];
        $west  = format_num($box->westBoundLongitude->Decimal);
        $east  = format_num($box->eastBoundLongitude->Decimal);
        $south = format_num($box->southBoundLatitude->Decimal);
        $north = format_num($box->northBoundLatitude->Decimal);
        echo "\t{\n";
        echo "\t\tid\t\t= ${epsg}\n";
        echo "\t\tbbox\t\t= [ $west, $east, $south, $north ]\n";
        echo "\t\tname\t\t= \"$name\"\n";
        if(isset($revision) && !empty($revision))
            echo "\t\trevision\t= \"$revision\"\n";
        if(isset($scope) && !empty($scope))
            echo "\t\tscope\t\t= \"$scope\"\n";
        if(isset($source) && !empty($source))
            echo "\t\tsource\t\t= \"$source\"\n";
        if(isset($deprecated))
            echo "\t\tdeprecated\t= $deprecated\n";
        echo "\t}";
    }
}
echo "\n)\n";

function esc($str)
{
    $tmp = str_replace("\n"," ",$str);
    $tmp = str_replace("\\","\\\\",$tmp);
    $tmp = str_replace('"','\"',$tmp);
    return $tmp;
}

function format_num($num)
{
    $num = (string) $num;
    if(strpos($num,".") === FALSE)
	$num = sprintf("%.1f",$num);
    return $num;
}
